# Generated by Django 4.2.5 on 2024-12-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Content", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="score",
            name="created_at",
        ),
        migrations.AddIndex(
            model_name="score",
            index=models.Index(
                fields=["user", "content"], name="Content_sco_user_id_9c5d93_idx"
            ),
        ),
    ]
