# Generated by Django 4.2.5 on 2024-12-04 08:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("Content", "0002_remove_score_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="score",
            name="Content_sco_user_id_9c5d93_idx",
        ),
        migrations.AddField(
            model_name="score",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
